config/routes.rb
Rails.application.routes.draw do
  #static pages via high_voltage

  resources :donations, only: [:new, :create]
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  after_create :send_confirmation

  def to_dollars
    self.amount_in_cents/100.to_f
  end

  private

    def send_confirmation
      DonationMailer.confirmation_email(self).deliver_later
    end
end

app/models/stripe_charger.rb
class StripeCharger
  attr_reader :customer_id

  def initialize(email:, amount:, token:)
    @email = email
    @amount = amount
    @token = token
    @donation = Donation.where(email: @email).take
  end

  def create_charge
    Stripe::Charge.create(
      amount: @amount,
      currency: "usd",
      customer: stripe_customer.id,
      description: "Donation to Children of Mexico International"
    )
    self
  end

  private

    def stripe_customer
      if @donation
        @customer_id = @donation.stripe_customer_id
        retrieve_stripe_customer
      else
        create_stripe_customer
      end
    end

    def create_stripe_customer
      Stripe::Customer.create(email: @email).tap do |sc|
        card = sc.sources.create(source: @token)
        sc.default_source = card.id
        @customer_id = sc.id
      end
    end

    def retrieve_stripe_customer
      Stripe::Customer.retrieve(@donation.stripe_customer_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  require "stripe"
  Stripe.api_key = ENV.fetch("STRIPE_SECRET")

  def new
    @donation = Donation.new
  end

  def create
    stripe_charger = StripeCharger.new(
      email: donation_params[:email],
      amount: donation_params[:amount_in_cents],
      token: params[:stripe_token]
    ).create_charge

    @donation = Donation.create(
      email: donation_params[:email],
      amount_in_cents: donation_params[:amount_in_cents],
      name: donation_params[:name],
      stripe_customer_id: stripe_charger.customer_id,
    )

    render partial: "/donations/success", locals: { donation: @donation }
  end

  private

    def donation_params
      params.require(:donation).permit(:email, :amount_in_cents, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="page-wrapper">
  <div class="well">
    <h1>
      <div class="horizontal divider page-header">About</div>
    </h1>
    <div class="about-images">
      <img class="active" src="https://s3-us-west-1.amazonaws.com/children-of-mexico/abouta2.JPG" />
      <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/abouta3.JPG" />
      <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/about5.JPG" />
      <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/about.JPG" />
      <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/about4.JPG" />
    </div>
    <div class="section-header">
      <h3>The Children of Mexico International Story</h3>
    </div>
    <p>On one of her many trips to Guadalajara, Mexico, California native and seasoned speech pathologist, Margarita Fajardo, had a life-altering experience when she visited an orphanage and met a young girl named Conchita. Conchita, born with cerebral palsy, was abandoned at the city dump.</p>
    <p>Fortunately a garbage collector found her and she was then given a home along with 19 other disabled children and young adults at a home called “Bienaventurados de Jesus.” The following year Margarita returned, bringing with her more therapists and equipment to help improve the lives of all the children there by enhancing their communication skills. Thus, Children of Mexico International was created.</p>
  </div>
</div>

app/views/application/_apply_button.html.erb
<div class="apply-button">
  <%= link_to "APPLY FOR 2023 MISSION", page_path('apply'), class: "basic-button negative" %>
</div>

app/views/application/_donate_button.html.erb
<div class="donate-button">
  <%= link_to "DONATE NOW", new_donation_path, class: "basic-button negative" %>
</div>

app/views/application/_footer.html.erb
<div class="footer">
  <div class="footer-items">
    <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/logo-horizontal.png" alt="">
    <div class="fb-button">
      <a class="basic-button primary" href="https://www.facebook.com/childrenofmex/" target="_blank">
        <p>Connect on Facebook</p>
        <i class="fa fa-facebook fa-2x" aria-hidden="true"></i>
      </a>
    </div>
  </div>

  <p>Children of Mexico International is a nonprofit, tax-exempt charitable organization under Section 501(c)(3) of the Internal Revenue Code.</p>
  <p>&copy;2016 Children of Mexico International. All rights reserved.</p>
  <p>Website by <a href="http://alookatommorow.github.io">John Hess</a></p>
</div>

app/views/application/_nav.html.erb
<header class="site-header">
  <nav class="stackable menu-container nav-menu">
    <div class="menu">
      <label for="show-menu" id="burger">
        <div class="menu-image">
          <img class="mobile-icon" src="https://s3-us-west-1.amazonaws.com/children-of-mexico/icon.svg" alt="">
          <img class="desk-icon" src="https://s3-us-west-1.amazonaws.com/children-of-mexico/horizontal-icon.svg" alt="">
        </div>
        <div class="menu-caret">
          <i class="fa fa-caret-down"></i>
          <i class="fa fa-caret-up"></i>
        </div>
      </label>
    </div>
    <input type="checkbox" id="show-menu" role=button>
    <div class="items">
      <%= link_to root_path, class: "item nav-item" do %>
        <p>Home</p>
      <% end %>
      <%= link_to page_path('apply'), class: "item nav-item" do %>
        <p>Apply</p>
      <% end %>
      <%= link_to page_path('about'), class: "item nav-item" do %>
        <p>About</p>
      <% end %>
      <%= link_to page_path('gallery'), class: "item nav-item" do %>
        <p>Gallery</p>
      <% end %>
      <%= link_to page_path('news'), class: "item nav-item"  do %>
        <p>News/Events</p>
      <% end %>
      <%= link_to page_path('contact'), class: "item nav-item"  do %>
        <p>Contact</p>
      <% end %>
      <%= link_to page_path('faq'), class: "item nav-item"  do %>
        <p>FAQ</p>
      <% end %>
      <%= link_to page_path('testimonials'), class: "item nav-item"  do %>
        <p>Testimonials</p>
      <% end %>
    </div>
  </nav>
</header>

app/views/contact/index.html.erb
<div class="page-wrapper">
  <div class="contact-container">
    <div class="well">
      <h1>
        <div class="horizontal divider">Contact</div>
      </h1>
      <form action="https://formspree.io/childrenofmex@gmail.com"
        method="POST" class="contact-form">
        <div class="field">
          <label class="label" for="name"><span class="asterisk">*</span> Full Name</label>
          <input type="text" placeholder="Full Name" name="name" class="validate name">
        </div>
        <div class="field">
          <label class="label" for="email"><span class="asterisk">*</span> Email</label>
          <input type="text" placeholder="Email" name="_replyto" class="validate email">
        </div>
        <div class="field">
          <label class="label" for="message"><span class="asterisk">*</span> Message</label>
          <textarea type="text" placeholder="Type your message here..." name="message" class="validate message"></textarea>
        </div>
        <input type="submit" value="Send" class="basic-button primary contact-button">
        <div class="error user-message"></div>
      </form>
      <div class="contact-success">

      </div>
      <div class="user-message success">Thank you for your inquiry. We will get back to you via email as soon as possible.</div>
    </div>
  </div>
</div>

app/views/donations/_success.html.erb
<div class="user-message success">
  <div class="header">
    Thank you for your donation of <%= number_to_currency(donation.to_dollars) %>.
  </div>
  <p>You will receive a confirmation at the email you provided.</p>
</div>

app/views/donations/new.html.erb
<div class="page-wrapper">
  <div class="well donate">
    <h1>
      <div class="horizontal divider">Donate</div>
    </h1>
    <form class="amount-form">
      <h3>Please enter a donation amount</h3>
      <div class="field">
        <label class="label" for="name"><span class="asterisk">*</span> Amount</label>
        <div class="validate amountList ax-select-dropdown">
          <i class="fa fa-angle-down"></i>
          <select class="ax-selector">
            <option>Choose an amount</option>
            <option value="10">$10</option>
            <option value="20">$20</option>
            <option value="50">$50</option>
            <option value="100">$100</option>
            <option value="other">Other amount</option>
          </select>
        </div>
      </div>
      <div class="field other-amount">
        <label class="label" for="name">Enter other amount:</label>
        <div class="amount-field">
          <i class="fa fa-usd"></i>
          <input type="text" placeholder="100" name="amount" class="validate amount">
        </div>
      </div>
      <input type="submit" value="Checkout" class="basic-button primary">
      <div class="error user-message"></div>
    </form>

    <div class="confirmation">
      <div class="confirmation-text">
        <div class="logo">
          <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/icon-padded.svg">
        </div>
        <div>
          <h3>Your card will be charged $<span class="confirm-amount"></span>.</h3>
        </div>
      </div>
      <div class="confirmation-buttons">
        <button id="donate-button" class="basic-button positive">Pay With Card</button>
        <h3>
          <div class="horizontal divider">Or</div>
        </h3>
        <button class="basic-button negative cancel-donation">Cancel</button>
      </div>
    </div>

    <div class="donation-success">
      <div class="loading-container">
        <h2>Processing...</h2>
        <i class="fa fa-spinner fa-pulse fa-3x fa-fw loader"></i>
      </div>
    </div>
    <div class="donation-info">
      <p><span>Children of Mexico International</span> is a nonprofit, tax-exempt charitable organization under Section 501(c)(3) of the Internal Revenue Code. Donations are tax-deductible as allowed by law.</p>
    </div>
  </div>
</div>
<script src="https://checkout.stripe.com/checkout.js"></script>

app/views/faq/index.html.erb
<div class="page-wrapper">
  <div class="well faq">
    <h1>
      <div class="horizontal divider page-header">Volunteer FAQ</div>
    </h1>

    <h3>Who volunteers? </h3>

    <p>Our volunteers range from monolingual English speakers to monolingual Spanish speakers and everything in between. We arrange teams of volunteers to accommodate the different levels of Spanish. While Mexico is a Catholic country and we attend mass in Sahuayo, our volunteers have been primarily non-Catholic. Volunteers have been both professionals and students in the fields of education, speech pathology, physical therapy, occupational therapy, and nursing. We welcome anyone who might have something to contribute to the lives of the children and professionals with whom we work in Mexico.</p>

    <h3>What is expected of volunteers?</h3>

    <p>In Guadalajara, we work at an orphanage where the children’s ages range from toddlers through adults, most of whom have severe cerebral palsy and spend much of their time in bed. We spend 3-4 hours per day at the orphanage, doing therapy with the children. Beyond that, volunteers have free time to sightsee, plan therapy activities, or spend more time helping the volunteer caregivers at the orphanage with the children’s daily routines. We have a party for the children on the last day so volunteers are encouraged to bring party ideas, favors, and/or small gifts.
    </p>

    <p>In Sahuayo, we perform hippotherapy in which the students are on horseback, traditional speech and language therapy, and we offer group presentations to parents and teachers from Sahuayo and surrounding towns. Students range in age from toddler to adult, with a variety of disorders, some of which may not have been diagnosed. The number of students attending is unpredictable, but we had approximately 80 students from surrounding towns in summer 2009. Volunteers work from 9:00am until approximately 4:00pm. Evenings are spent helping each other prepare presentations or therapy, programming AAC devices, or relaxing and having “cena.” Volunteers are asked to let us know in advance if they would like to present to parents or teachers, work with horses, perform therapy, and/or assess the students, or entertain children while they wait for therapy. </p>

    <h3>What should I bring?</h3>

    <p>Bring materials you would like to use for a variety of therapy. If you can copy or donate materials to the local teachers and parents for use once we leave, that is even better. Bring stickers, bubbles, candy, small toys, school supplies and/or backpacks to give to students. Children of Mexico Intl. keeps materials at the Guadalajara site for use at the orphanage. All sizes of clothing in good condition is also desirable to donate in both cities. </p>

    <p>Bring personal items such as an umbrella, guidebook, backpack to carry materials from our hotel to our work sites, and a laptop for creating materials or making presentations.
    </p>

    <h3>What should I wear?</h3>

    <p>Please dress conservatively and professionally during daily interactions with students, parents, and teachers. In Guadalajara, slacks and shirts with sleeves are appropriate. In Sahuayo, jeans may also be appropriate if working with horses. Please no short skirts, shorts, or tank tops. Bring at least one dressy outfit (dress or nice pants) for the fundraising dinner in Guadalajara and/or mass in Sahuayo. In the past, some volunteers have brought clothes to wear that they were planning to get rid of anyway. At the end of the time in Mexico, these clothes are donated to locals. There are laundries in Sahuayo that will wash and dry your clothes for you in less than a day. We have Children of Mexico Intl. shirts for purchase that are appropriate for wear while working. These are optional. It often rains in the afternoons in both areas so a raincoat is useful.</p>

    <h3>Where do we stay?</h3>

    <p>In Guadalajara, we stay at the Country Plaza Inn in Zapopan. It is approximately a 20 minute walk or a 5 minute taxi ride to the orphanage. There is a restaurant in the hotel and there are many others close by. It is a 10 minute walk to the main plaza and market of Zapopan. It is also a 10 minute walk to Plaza Patria, a shopping mall with all necessities.</p>

    <p>In Sahuayo, we are hosted by the local diocese and stay in one of the hotels in town to be determined by our hosts. Local adult participants provide the afternoon “comida” for everyone. The evening “cena” is provided by church volunteers at the rectory for our volunteers. Sahuayo is a small town and all necessities are within an easy walk of the hotel.</p>

    <h3>How do I communicate with home?</h3>

    <p>Phone calls to the United States are expensive and sometimes difficult to make. It is recommended that volunteers plan on using skype or email to communicate, although the internet can be slow.</p>

    <h3>What if I get sick or injured?</h3>

    <p>Pharmacies are conveniently located in both areas, but it is recommended that you come with medications in case of emergency. The Clínica San Francisco next to Plaza Patria in Guadalajara provides excellent, inexpensive care in case of emergency. Emergency information cards will be given to all volunteers.
    </p>

    <h3>Is it safe?</h3>

    <p>Michoacan is a large state and the Sahuayo area is distant from problem areas. Common sense and precautions are taken to be safe and not to travel on rural highways after dark. Guadalajara is a relatively safe city, but traffic is heavy and pedestrians DO NOT have the right of way when crossing streets in Mexico. Please use caution when doing so.</p>

    <h3>How much money do will I need?</h3>

    <p>Enough to cover meals in Guadalajara, hotels (price to be determined), taxis in Guadalajara (approx. $6.00) round trip per taxi to the orphanage, approx. $10.00 round trip to downtown), excess for sightseeing, museum and concert entry fees if desired.</p>
  </div>
</div>

app/views/gallery/index.html.erb
<div class="page-wrapper">
  <div class="well gallery">
    <h1>
      <div class="horizontal divider">Gallery</div>
    </h1>
    <div class="gallery-menu" data-content-container=".gallery-content">
      <a class="item active" data-gallery-link="photo">Photos</a>
      <a class="item" data-gallery-link="video">Videos</a>
      <a class="item" data-gallery-link="press">Press</a>
    </div>
    <div class="gallery-content">
      <%= render partial: "photos" %>
      <%= render partial: "videos" %>
      <%= render partial: "press" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="home">
  <div class="well">
    <div class="logo-container-mobile">
      <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/horizontal-icon.svg" alt="">
    </div>
    <div class="carousel-container">
      <div class="photo-container">
      </div>
      <div class="dots-container">
        <div class="circle-container">
          <div class="circle first active"></div>
        </div>
        <div class="circle-container">
          <div class="circle"></div>
        </div>
        <div class="circle-container">
          <div class="circle"></div>
        </div>
        <div class="circle-container">
          <div class="circle"></div>
        </div>
        <div class="circle-container">
          <div class="circle"></div>
        </div>
      </div>
    </div>
    <div class="welcome-container">
      <div class="logo-container">
        <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/logo.svg" alt="">
      </div>
      <div class="divider"></div>
      <div class="text-container">
        <!-- <h1>
          <div class="horizontal divider">Welcome</div>
        </h1> -->
        <p>Children of Mexico International is committed to enhancing the lives of children and young adults by sharing evidence-based communication techniques, therapy materials and equipment, education and research to those with a need.</p>
        <p>Children of Mexico International currently serves children in an orphanage in Guadalajara, and at a central location in Sahuayo, Mexico. In Guadalajara, augmentative and alternative communication (AAC) techniques are emphasized and in Sahuayo, hippotherapy, the practice of using the therapeutic movement of the horse to strengthen core muscles and improve balance, is one of the strategies being used.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Children Of Mexico International</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= favicon_link_tag 'favicon.ico' %>
  <script>Stripe.setPublishableKey('<%= ENV.fetch("STRIPE_PUBLIC") %>')</script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render partial: "nav" %>
  <div class="buttons-container">
    <%= render partial: "apply_button" %>
    <%= render partial: "donate_button" %>
  </div>
  
  <div class="page-content">
    <%= yield %>
  </div>
  <%= render partial: "footer" %>
</body>
</html>

app/views/pages/_photos.html.erb
<div id="photo" class="active">
  <div class="photo-menu" data-content-container=".photo-content">
    <a class="item active" data-photo-link="allPhotos">All</a>
    <a class="item" data-photo-link="sixteen">2016</a>
    <a class="item" data-photo-link="fifteen">2015</a>
  </div>
  <div class="photo-content">
    <div class="carousel-button prev" data-carousel="prev">
      <i class="fa fa-angle-left" ></i>
    </div>
    <div class="carousel-button next" data-carousel="next">
      <i class="fa fa-angle-right " ></i>
    </div>

    <div id="allPhotos" class="photo-group active">
      <div class="carousel-image-container"></div>
      <div class="photo-thumbnails"></div>
    </div>
    <div id="sixteen" class="photo-group">
      <div class="carousel-image-container"></div>
      <div class="photo-thumbnails"></div>
    </div>
    <div id="fifteen" class="photo-group">
      <div class="carousel-image-container"></div>
      <div class="photo-thumbnails"></div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="page-wrapper">
  <div class="well">
    <h1>
      <div class="horizontal divider page-header">About</div>
    </h1>
    <div class="about-images">
      <img class="active" src="https://s3-us-west-1.amazonaws.com/children-of-mexico/abouta2.JPG" />
      <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/abouta3.JPG" />
      <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/about5.JPG" />
      <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/about.JPG" />
      <img src="https://s3-us-west-1.amazonaws.com/children-of-mexico/about4.JPG" />
    </div>
    <div class="section-header">
      <h3>The Children of Mexico International Story</h3>
    </div>
    <p>On one of her many trips to Guadalajara, Mexico, California native and seasoned speech pathologist, Margarita Fajardo, had a life-altering experience when she visited an orphanage and met a young girl named Conchita. Conchita, born with cerebral palsy, was abandoned at the city dump.</p>
    <p>Fortunately a garbage collector found her and she was then given a home along with 19 other disabled children and young adults at a home called “Bienaventurados de Jesus.” The following year Margarita returned, bringing with her more therapists and equipment to help improve the lives of all the children there by enhancing their communication skills. Thus, Children of Mexico International was created.</p>
  </div>
</div>

app/views/pages/apply.html.erb
<div class="page-wrapper">
  <div class="well apply">
    <h1>
      <div class="horizontal divider page-header">Apply</div>
    </h1>
    <div>
      <h3>Join us for our 2023 Mission to Mexico!</h3>
      <p>Bring joy to disabled and orphaned children or learn about hippotherapy and its benefit for disabled individuals.</p>
      <p>The mission fee is due by March 30, 2023.</p>
      <p>Please download the application and send it with deposit and other documents to:</p>
      <div class="address">
        <p>Children of Mexico International</p>
        <p>C/O Margarita Fajardo</p>
        <p>524 Hemlock Ave</p>
        <p>South San Francisco, CA 94080</p>
      </div>
      <div class="download">
        <a href="https://children-of-mexico.s3.us-west-1.amazonaws.com/COMI-2023-application.pdf">
          <img src="https://children-of-mexico.s3.us-west-1.amazonaws.com/comi-2023-icon.png" alt="2023 application">
          <i class='fa fa-3x fa-download' aria-hidden='true'></i>
          <div>Download Application</div>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="page-wrapper">
  <div class="contact-container">
    <div class="well">
      <h1>
        <div class="horizontal divider">Contact</div>
      </h1>
      <form action="https://formspree.io/childrenofmex@gmail.com"
        method="POST" class="contact-form">
        <div class="field">
          <label class="label" for="name"><span class="asterisk">*</span> Full Name</label>
          <input type="text" placeholder="Full Name" name="name" class="validate name">
        </div>
        <div class="field">
          <label class="label" for="email"><span class="asterisk">*</span> Email</label>
          <input type="text" placeholder="Email" name="_replyto" class="validate email">
        </div>
        <div class="field">
          <label class="label" for="message"><span class="asterisk">*</span> Message</label>
          <textarea type="text" placeholder="Type your message here..." name="message" class="validate message"></textarea>
        </div>
        <input type="submit" value="Send" class="basic-button primary contact-button">
        <div class="error user-message"></div>
      </form>
      <div class="contact-success">

      </div>
      <div class="user-message success">Thank you for your inquiry. We will get back to you via email as soon as possible.</div>
    </div>
  </div>
</div>

app/views/pages/faq.html.erb
<div class="page-wrapper">
  <div class="well faq">
    <h1>
      <div class="horizontal divider page-header">Volunteer FAQ</div>
    </h1>

    <h3>Who volunteers? </h3>

    <p>Our volunteers range from monolingual English speakers to monolingual Spanish speakers and everything in between. We arrange teams of volunteers to accommodate the different levels of Spanish. While Mexico is a Catholic country and we attend mass in Sahuayo, our volunteers have been primarily non-Catholic. Volunteers have been both professionals and students in the fields of education, speech pathology, physical therapy, occupational therapy, and nursing. We welcome anyone who might have something to contribute to the lives of the children and professionals with whom we work in Mexico.</p>

    <h3>What is expected of volunteers?</h3>

    <p>In Guadalajara, we work at an orphanage where the children’s ages range from toddlers through adults, most of whom have severe cerebral palsy and spend much of their time in bed. We spend 3-4 hours per day at the orphanage, doing therapy with the children. Beyond that, volunteers have free time to sightsee, plan therapy activities, or spend more time helping the volunteer caregivers at the orphanage with the children’s daily routines. We have a party for the children on the last day so volunteers are encouraged to bring party ideas, favors, and/or small gifts.
    </p>

    <p>In Sahuayo, we perform hippotherapy in which the students are on horseback, traditional speech and language therapy, and we offer group presentations to parents and teachers from Sahuayo and surrounding towns. Students range in age from toddler to adult, with a variety of disorders, some of which may not have been diagnosed. The number of students attending is unpredictable, but we had approximately 80 students from surrounding towns in summer 2009. Volunteers work from 9:00am until approximately 4:00pm. Evenings are spent helping each other prepare presentations or therapy, programming AAC devices, or relaxing and having “cena.” Volunteers are asked to let us know in advance if they would like to present to parents or teachers, work with horses, perform therapy, and/or assess the students, or entertain children while they wait for therapy. </p>

    <h3>What should I bring?</h3>

    <p>Bring materials you would like to use for a variety of therapy. If you can copy or donate materials to the local teachers and parents for use once we leave, that is even better. Bring stickers, bubbles, candy, small toys, school supplies and/or backpacks to give to students. Children of Mexico Intl. keeps materials at the Guadalajara site for use at the orphanage. All sizes of clothing in good condition is also desirable to donate in both cities. </p>

    <p>Bring personal items such as an umbrella, guidebook, backpack to carry materials from our hotel to our work sites, and a laptop for creating materials or making presentations.
    </p>

    <h3>What should I wear?</h3>

    <p>Please dress conservatively and professionally during daily interactions with students, parents, and teachers. In Guadalajara, slacks and shirts with sleeves are appropriate. In Sahuayo, jeans may also be appropriate if working with horses. Please no short skirts, shorts, or tank tops. Bring at least one dressy outfit (dress or nice pants) for the fundraising dinner in Guadalajara and/or mass in Sahuayo. In the past, some volunteers have brought clothes to wear that they were planning to get rid of anyway. At the end of the time in Mexico, these clothes are donated to locals. There are laundries in Sahuayo that will wash and dry your clothes for you in less than a day. We have Children of Mexico Intl. shirts for purchase that are appropriate for wear while working. These are optional. It often rains in the afternoons in both areas so a raincoat is useful.</p>

    <h3>Where do we stay?</h3>

    <p>In Guadalajara, we stay at the Country Plaza Inn in Zapopan. It is approximately a 20 minute walk or a 5 minute taxi ride to the orphanage. There is a restaurant in the hotel and there are many others close by. It is a 10 minute walk to the main plaza and market of Zapopan. It is also a 10 minute walk to Plaza Patria, a shopping mall with all necessities.</p>

    <p>In Sahuayo, we are hosted by the local diocese and stay in one of the hotels in town to be determined by our hosts. Local adult participants provide the afternoon “comida” for everyone. The evening “cena” is provided by church volunteers at the rectory for our volunteers. Sahuayo is a small town and all necessities are within an easy walk of the hotel.</p>

    <h3>How do I communicate with home?</h3>

    <p>Phone calls to the United States are expensive and sometimes difficult to make. It is recommended that volunteers plan on using skype or email to communicate, although the internet can be slow.</p>

    <h3>What if I get sick or injured?</h3>

    <p>Pharmacies are conveniently located in both areas, but it is recommended that you come with medications in case of emergency. The Clínica San Francisco next to Plaza Patria in Guadalajara provides excellent, inexpensive care in case of emergency. Emergency information cards will be given to all volunteers.
    </p>

    <h3>Is it safe?</h3>

    <p>Michoacan is a large state and the Sahuayo area is distant from problem areas. Common sense and precautions are taken to be safe and not to travel on rural highways after dark. Guadalajara is a relatively safe city, but traffic is heavy and pedestrians DO NOT have the right of way when crossing streets in Mexico. Please use caution when doing so.</p>

    <h3>How much money do will I need?</h3>

    <p>Enough to cover meals in Guadalajara, hotels (price to be determined), taxis in Guadalajara (approx. $6.00) round trip per taxi to the orphanage, approx. $10.00 round trip to downtown), excess for sightseeing, museum and concert entry fees if desired.</p>
  </div>
</div>

app/views/pages/gallery.html.erb
<div class="page-wrapper">
  <div class="well gallery">
    <h1>
      <div class="horizontal divider">Gallery</div>
    </h1>
    <div class="gallery-menu" data-content-container=".gallery-content">
      <a class="item active" data-gallery-link="photo">Photos</a>
      <a class="item" data-gallery-link="video">Videos</a>
      <a class="item" data-gallery-link="press">Press</a>
    </div>
    <div class="gallery-content">
      <%= render partial: "pages/photos" %> <!-- refactor? -->
      <%= render partial: "pages/videos" %>
      <%= render partial: "pages/press" %>
    </div>
  </div>
</div>

app/views/pages/news.html.erb
<div class="page-wrapper">
  <div class="well">
    <h1>
      <div class="horizontal divider page-header">News and Events</div>
    </h1>
  </div>
</div>